### ISSUE TITLE
您好，想请教一下预训练模型无法从checkpoint加载权重的问题

### ISSUE THREAD

**Issue by zl0717** [Jacen789/relation-extraction#10]
![截屏2022-06-08 下午3 03 07](https://user-images.githubusercontent.com/91644276/172552958-5d4720e4-828c-41b0-b4bf-2e08d0e5b8f2.png)

**Comment by Jacen789** [comment]
你加载模型的路径是什么，目录下有什么？

**Comment by zl0717** [comment]
预训练模型的路径就是"/tmp/pycharm_project_55/relation-extraction-master/pretrained_models/bert-base-chinese" 您是指这个路径吗？ 另外目录是指？

**Comment by zl0717** [comment]
![172552958-5d4720e4-828c-41b0-b4bf-2e08d0e5b8f2](https://user-images.githubusercontent.com/91644276/173233001-a327fc1e-1e70-4618-a366-a850965ef23e.png)
想请问一下是和红色方框中的路径有关系吗 我们不是已经下载了预训练模型并且从自己的文件夹路径中调出了吗

**Comment by zl0717** [comment]
![mmexport1655036758978](https://user-images.githubusercontent.com/91644276/173233154-4e66ca10-64d1-444c-8589-6ab2484dd7f9.png)
想请问一下是和红色方框中的路径有关系吗 我们不是已经下载了预训练模型并且从自己的文件夹路径中调出了吗

**Comment by zl0717** [comment]
![mmexport1655041498850](https://user-images.githubusercontent.com/91644276/173236246-9144ae44-2566-4a7f-bc12-45fad7f02583.png)
另外还有一条报错信息是这样的
网上说是预训练模型权重未下载完毕导致的 但我们不是已经下载好预训练模型了吗 这又应该怎么处理呢

**Comment by Jacen789** [comment]
这些问题不是模型没下载完，就是文件夹写错名字，还有文件夹下的文件不全，比如少了vocab.txt，或者是模型文件的名字不对导致的
