### ISSUE TITLE
警告

### ISSUE THREAD

**Issue by wangguanhua** [Jacen789/relation-extraction#3]
程序正常运行，但shell上显示警告，如下所示
Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.

**Comment by wuyang45** [comment]
请问这个问题解决了吗

**Comment by wuyang45** [comment]
> 程序正常运行，但shell上显示警告，如下所示
> Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.

请问这个问题解决了吗，是什么原因呢

**Comment by xzc721** [comment]
我也遇到这个问题，请问你解决了吗？

**Comment by wangguanhua** [comment]
版本问题，无视就好。GitHub上transformers仓库issue里有人提到了，也给出了解决方案，你可以去看看


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jacen789/relation-extraction"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月3日(星期四) 下午2:46
收件人:&nbsp;"Jacen789/relation-extraction"<relation-extraction@noreply.github.com&gt;;
抄送:&nbsp;"767477036"<767477036@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Jacen789/relation-extraction] 警告 (#3)





 
我也遇到这个问题，请问你解决了吗？

**Comment by xzc721** [comment]
好的，非常感谢！
