### ISSUE TITLE
TypeError: bmm(): argument 'mat2' (position 2) must be Tensor, not str

### ISSUE THREAD

**Issue by Fheon** [Jacen789/relation-extraction#4]
先谢谢大佬开源项目。我跑代码的时候发现代码有错，在model.py的倒数第三行sum_vector = torch.bmm(e_mask_unsqueeze.float(), hidden_output).squeeze(1)会报错：这里的hidden_output的值是“last_hidden_state”，是一个字符串，不是Tensor。请问是怎么一回事。

**Comment by Jacen789** [comment]
你看看你model.py中forward的第一行代码是否正确？或者有一种可能就是transformers的BertModel的forward输出改了？

**Comment by Fheon** [comment]
> 
> 
> 你看看你model.py中forward的第一行代码是否正确？或者有一种可能就是transformers的BertModel的forward输出改了？

和您的源码一致：
    def forward(self, token_ids, token_type_ids, attention_mask, e1_mask, e2_mask):
        sequence_output, pooled_output = self.bert_model(token_ids, token_type_ids, attention_mask)
请问您的tramsformers版本是多少？

**Comment by Jacen789** [comment]
你能把你的报错信息全部发出来看一下吗？

**Comment by Jacen789** [comment]
已经修复了因transformers版本更新导致的兼容性问题。
