### ISSUE TITLE
是否需要添加[SEP]token

### ISSUE THREAD

**Issue by hitmancx** [Jacen789/relation-extraction#5]
data_utils中78行与161是否重复，两者同时存在会让句子出现两个[SEP]

**Comment by Jacen789** [comment]
其实79行已经把加上的[SEP]切掉了。

**Comment by hitmancx** [comment]
您好像只是切了[CLS]啊，对re_token还是取到了最后一个

**Comment by hitmancx** [comment]
> 其实79行已经把加上的[SEP]切掉了。

首先感谢您的回复，第79行，您好像只是切了[CLS]，对re_token还是取到了最后一个

**Comment by hitmancx** [comment]
> 其实79行已经把加上的[SEP]切掉了。

感谢回答
