### ISSUE TITLE
你好，做validation和predict的时候有用到saved_models保存的模型吗

### ISSUE THREAD

**Issue by Yu-Yuqing** [Jacen789/relation-extraction#8]
我在您的代码里没有具体看到，如train.py的86行开始，看到传入的还是pretrained_model_path，方便指明一下哪部分代码是调用了saved_models的模型的吗？谢谢！

>         if validation_file:
            validation_dataset = SentenceREDataset(validation_file, tagset_path=tagset_file,
                                                   pretrained_model_path=pretrained_model_path,
                                                   max_len=max_len)

**Comment by Jacen789** [comment]
推理的时候，可以看demo_predict.py，relation_extraction.predict中的predict函数。
