### ISSUE TITLE
您好想请问一下为什么加载预训练模型一直有问题呢

### ISSUE THREAD

**Issue by zl0717** [Jacen789/relation-extraction#9]
![1654414441003](https://user-images.githubusercontent.com/91644276/172040454-f92616a3-de8e-4578-a47a-74076687689a.jpg)
![1654414501938](https://user-images.githubusercontent.com/91644276/172040487-dc376d7d-550e-4656-ae6e-013e2dd55ca4.jpg)
![Uploading 1654414531029.jpg…]()

**Comment by Jacen789** [comment]
你的路径"/tmp/pycharm_project_55/relation-extraction-master/pretrained_models/bert-base-chinese"下的文件可以发出来看一下吗？

**Comment by zl0717** [comment]
![Uploading 1654519600821.jpg…]()

**Comment by zl0717** [comment]
![mmexport1654418520195](https://user-images.githubusercontent.com/91644276/172175209-7d55dafb-47da-4e58-a84c-ba4a10894b42.jpg)

**Comment by Jacen789** [comment]
> ![mmexport1654418520195](https://user-images.githubusercontent.com/91644276/172175209-7d55dafb-47da-4e58-a84c-ba4a10894b42.jpg)

把bert_base_chinese文件夹的名字改成bert-base-chinese。"_"改成"-"。

**Comment by zl0717** [comment]
> > ![mmexport1654418520195](https://user-images.githubusercontent.com/91644276/172175209-7d55dafb-47da-4e58-a84c-ba4a10894b42.jpg)
> 
> 把bert_base_chinese文件夹的名字改成bert-base-chinese。"_"改成"-"。

问题解决了，十分感谢。
